services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_NAME=logs_db
      - DB_USER=logs_user
      - DB_PASSWORD=logs_password
      - DB_PORT=5432
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=logs_user
      - POSTGRES_PASSWORD=logs_password
      - POSTGRES_DB=logs_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
